allowBuilds:
  '@apollo/protobufjs': set this to true or false
  '@firebase/util': set this to true or false
  '@hebilicious/form-actions-nuxt': set this to true or false
  '@hebilicious/server-block-nuxt': set this to true or false
  '@morev/vue-transitions': set this to true or false
  '@parcel/watcher': false
  '@prisma/client': set this to true or false
  '@swc/core': set this to true or false
  '@tailwindcss/oxide': false
  '@varlet/nuxt': set this to true or false
  '@vexip-ui/nuxt': set this to true or false
  bcrypt: set this to true or false
  better-sqlite3: set this to true or false
  cbor-extract: set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  esbuild: false
  maplibre-gl: set this to true or false
  msgpackr-extract: set this to true or false
  nuxt-hue: set this to true or false
  nuxt-openapi-docs-module: set this to true or false
  nuxt-users: set this to true or false
  protobufjs: set this to true or false
  sharp: set this to true or false
  ttf2woff2: set this to true or false
  unrs-resolver: false
  vue-demi: false
  yarn: set this to true or false
minimumReleaseAgeExclude:
  - '@vueform/builder-nuxt@1.40.0'
  - '@vueform/builder@1.12.14'
  - '@vueform/nuxt@1.31.0'
  - '@vueform/vueform@1.13.13'
