import amqplib, { Channel, ChannelModel, ConsumeMessage } from 'amqplib';
import { config } from '../config';
import { logger } from '../lib/logger';
import { GenerationService } from '../services/generation.service';
import { GenerationType } from '../models/generation.model';

interface DocumentCreatedPayload {
  documentId: string;
  projectId?: string;
  userId: string;
  title: string;
  content?: string;
  contentType?: string;
  autoGenerateDocs?: boolean;
}

interface IncomingEvent {
  eventType: string;
  timestamp: string;
  source: string;
  payload: unknown;
}

export class AIConsumer {
  private connection: ChannelModel | null = null;
  private channel: Channel | null = null;
  private readonly generationService: GenerationService;

  constructor(generationService: GenerationService) {
    this.generationService = generationService;
  }

  async start(): Promise<void> {
    const MAX_RETRIES = 5;
    const RETRY_DELAY_MS = 5000;

    for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
      try {
        await this.connect();
        logger.info('AI consumer started');

        return;
      } catch (error) {
        const err = error instanceof Error ? error : new Error(String(error));
        logger.error(`AI consumer connection attempt ${attempt}/${MAX_RETRIES} failed`, {
          error: err.message,
        });

        if (attempt < MAX_RETRIES) {
          await new Promise<void>((resolve) => setTimeout(resolve, RETRY_DELAY_MS));
        } else {
          logger.error('AI consumer: max retries reached. Consumer will not start.');
        }
      }
    }
  }

  private async connect(): Promise<void> {
    this.connection = await amqplib.connect(config.rabbitmq.url);
    this.channel = await this.connection.createChannel();

    await this.channel.assertExchange(config.rabbitmq.exchange, 'topic', {
      durable: true,
    });

    const { queue } = await this.channel.assertQueue(config.rabbitmq.queue, {
      durable: true,
      arguments: {
        'x-message-ttl': 24 * 60 * 60 * 1000, // 24 hours
        'x-dead-letter-exchange': `${config.rabbitmq.exchange}.dlx`,
      },
    });

    // Bind to document-created events
    await this.channel.bindQueue(queue, config.rabbitmq.exchange, 'document.created');

    // Process one message at a time
    this.channel.prefetch(1);

    await this.channel.consume(queue, (msg: ConsumeMessage | null) => {
      if (msg) {
        void this.handleMessage(msg);
      }
    });

    this.connection.on('error', (err: Error) => {
      logger.error('RabbitMQ connection error (consumer)', { error: err.message });
    });

    this.connection.on('close', () => {
      logger.warn('RabbitMQ connection closed (consumer). Attempting reconnect...');
      setTimeout(() => void this.start(), 5000);
    });
  }

  private async handleMessage(msg: ConsumeMessage): Promise<void> {
    if (!this.channel) {return;}

    try {
      const body = JSON.parse(msg.content.toString()) as IncomingEvent;
      logger.debug('Received event', { eventType: body.eventType });

      if (body.eventType === 'document.created') {
        await this.handleDocumentCreated(body.payload as DocumentCreatedPayload);
      }

      this.channel.ack(msg);
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      logger.error('Failed to process consumer message', { error: err.message });
      // Nack without requeue on parse/logic error; requeue on infrastructure error
      const requeue = err.message.includes('ECONNREFUSED') || err.message.includes('timeout');
      this.channel.nack(msg, false, requeue);
    }
  }

  private async handleDocumentCreated(payload: DocumentCreatedPayload): Promise<void> {
    // Only trigger auto-generation if the document requests it
    if (!payload.autoGenerateDocs) {
      logger.debug('DocumentCreated: auto-generation not requested, skipping', {
        documentId: payload.documentId,
      });

      return;
    }

    if (!payload.content || payload.content.trim() === '') {
      logger.debug('DocumentCreated: empty content, skipping auto-generation', {
        documentId: payload.documentId,
      });

      return;
    }

    logger.info('DocumentCreated: triggering auto-generation', {
      documentId: payload.documentId,
      userId: payload.userId,
    });

    try {
      const { jobId } = await this.generationService.requestGeneration(payload.userId, {
        type: GenerationType.FULL_DOCS,
        content: payload.content,
        context: `Document title: ${payload.title}`,
        documentId: payload.documentId,
        projectId: payload.projectId,
      });

      logger.info('Auto-generation job queued', {
        documentId: payload.documentId,
        jobId,
      });
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      logger.error('Auto-generation request failed', {
        documentId: payload.documentId,
        error: err.message,
      });
      // Do not re-throw — a failed auto-generation should not fail the consumer
    }
  }

  async stop(): Promise<void> {
    try {
      if (this.channel) {await this.channel.close();}
      if (this.connection) {await this.connection.close();}
      this.channel = null;
      this.connection = null;
      logger.info('AI consumer stopped');
    } catch (error) {
      const err = error instanceof Error ? error : new Error(String(error));
      logger.error('Error stopping AI consumer', { error: err.message });
    }
  }
}
