import { marked } from 'marked';
import { IExporter, ExportableDocument } from './exporter.interface';
import { ExportOptions } from '../models/exportJob.model';
import { logger } from '../lib/logger';

export class HtmlExporter implements IExporter {
  async export(document: ExportableDocument, options: ExportOptions): Promise<Buffer> {
    logger.debug('HtmlExporter.export called', { documentId: document.id });

    const bodyContent = await this.renderContent(document.content);
    const toc = options.includeTableOfContents ? this.buildToc(document.content) : '';
    const metaBlock = options.includeMetadata ? this.buildMetaBlock(document) : '';
    const watermarkHtml = options.watermark
      ? `<div class="watermark">${this.escapeHtml(options.watermark)}</div>`
      : '';

    const theme = options.theme ?? 'default';
    const css = this.getCss(theme);

    const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta name="generator" content="DevDocs Studio Export Service" />
  <title>${this.escapeHtml(document.title)}</title>
  <style>
${css}
  </style>
</head>
<body>
${watermarkHtml}
<div class="container">
  <header class="doc-header">
    <h1 class="doc-title">${this.escapeHtml(document.title)}</h1>
${metaBlock}
  </header>
${toc}
  <main class="doc-content">
${bodyContent}
  </main>
  <footer class="doc-footer">
    <p>Generated by <strong>DevDocs Studio</strong></p>
  </footer>
</div>
</body>
</html>`;

    return Buffer.from(html, 'utf-8');
  }

  // ── Private helpers ────────────────────────────────────

  private async renderContent(content: string): Promise<string> {
    // If content looks like HTML already, return as-is
    if (/<[a-z][\s\S]*>/i.test(content)) {
      return content;
    }
    // Otherwise treat as Markdown
    const rendered = await marked.parse(content);

    return rendered;
  }

  private buildToc(content: string): string {
    // Extract headings from Markdown
    const headingRegex = /^(#{1,6})\s+(.+)$/gm;
    const items: string[] = [];
    let match: RegExpExecArray | null;

    while ((match = headingRegex.exec(content)) !== null) {
      const level = match[1].length;
      const title = match[2].trim();
      const anchor = this.toAnchor(title);
      const indent = '  '.repeat(level - 1);
      items.push(`${indent}<li><a href="#${anchor}">${this.escapeHtml(title)}</a></li>`);
    }

    if (items.length === 0) {return '';}

    return `  <nav class="toc" aria-label="Table of Contents">
    <h2 class="toc-title">Table of Contents</h2>
    <ul class="toc-list">
      ${items.join('\n      ')}
    </ul>
  </nav>`;
  }

  private buildMetaBlock(document: ExportableDocument): string {
    const items: string[] = [];
    if (document.author) {
      items.push(`<span class="meta-item"><strong>Author:</strong> ${this.escapeHtml(document.author)}</span>`);
    }
    if (document.createdAt) {
      items.push(
        `<span class="meta-item"><strong>Created:</strong> ${document.createdAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>`,
      );
    }
    if (document.updatedAt) {
      items.push(
        `<span class="meta-item"><strong>Updated:</strong> ${document.updatedAt.toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</span>`,
      );
    }
    if (document.tags && document.tags.length > 0) {
      const tagHtml = document.tags
        .map((t) => `<span class="tag">${this.escapeHtml(t)}</span>`)
        .join(' ');
      items.push(`<span class="meta-item"><strong>Tags:</strong> ${tagHtml}</span>`);
    }
    if (document.metadata?.readingTimeMinutes !== undefined) {
      items.push(`<span class="meta-item"><strong>Reading time:</strong> ${document.metadata.readingTimeMinutes} min</span>`);
    }

    if (items.length === 0) {return '';}

    return `    <div class="doc-meta">${items.join(' &bull; ')}</div>`;
  }

  private toAnchor(text: string): string {
    return text
      .toLowerCase()
      .replace(/[^\w\s-]/g, '')
      .replace(/\s+/g, '-');
  }

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;')
      .replace(/'/g, '&#39;');
  }

  private getCss(theme: string): string {
    const base = `
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, sans-serif; font-size: 16px; line-height: 1.7; }
    .container { max-width: 860px; margin: 0 auto; padding: 2rem 1.5rem 4rem; }
    .doc-header { margin-bottom: 2.5rem; padding-bottom: 1.5rem; border-bottom: 1px solid var(--border); }
    .doc-title { font-size: 2.2rem; font-weight: 700; color: var(--heading); margin-bottom: 0.75rem; }
    .doc-meta { font-size: 0.875rem; color: var(--muted); }
    .meta-item { margin-right: 0.5rem; }
    .tag { display: inline-block; background: var(--tag-bg); color: var(--tag-text); padding: 0.1rem 0.5rem; border-radius: 4px; font-size: 0.8rem; margin-right: 0.25rem; }
    .toc { background: var(--toc-bg); border: 1px solid var(--border); border-radius: 6px; padding: 1.25rem 1.5rem; margin-bottom: 2rem; }
    .toc-title { font-size: 1rem; font-weight: 600; margin-bottom: 0.75rem; color: var(--heading); }
    .toc-list { list-style: none; }
    .toc-list li { margin: 0.3rem 0; }
    .toc-list a { color: var(--link); text-decoration: none; font-size: 0.9rem; }
    .toc-list a:hover { text-decoration: underline; }
    .doc-content h1, .doc-content h2, .doc-content h3, .doc-content h4, .doc-content h5, .doc-content h6 { color: var(--heading); font-weight: 700; line-height: 1.3; margin: 1.75rem 0 0.75rem; }
    .doc-content h1 { font-size: 1.9rem; }
    .doc-content h2 { font-size: 1.5rem; border-bottom: 1px solid var(--border); padding-bottom: 0.35rem; }
    .doc-content h3 { font-size: 1.2rem; }
    .doc-content p { margin-bottom: 1rem; }
    .doc-content a { color: var(--link); }
    .doc-content a:hover { text-decoration: underline; }
    .doc-content code { background: var(--code-bg); color: var(--code-text); padding: 0.15em 0.4em; border-radius: 3px; font-family: 'SFMono-Regular', Consolas, 'Liberation Mono', Menlo, monospace; font-size: 0.875em; }
    .doc-content pre { background: var(--pre-bg); padding: 1rem 1.25rem; border-radius: 6px; overflow-x: auto; margin: 1.25rem 0; }
    .doc-content pre code { background: none; padding: 0; color: inherit; }
    .doc-content blockquote { border-left: 4px solid var(--accent); margin: 1rem 0; padding: 0.5rem 1rem; color: var(--muted); font-style: italic; }
    .doc-content ul, .doc-content ol { margin: 0.75rem 0 0.75rem 1.5rem; }
    .doc-content li { margin-bottom: 0.35rem; }
    .doc-content table { width: 100%; border-collapse: collapse; margin: 1.25rem 0; }
    .doc-content th, .doc-content td { border: 1px solid var(--border); padding: 0.6rem 0.85rem; text-align: left; }
    .doc-content th { background: var(--toc-bg); font-weight: 600; }
    .doc-content img { max-width: 100%; height: auto; border-radius: 4px; }
    .doc-content hr { border: none; border-top: 1px solid var(--border); margin: 2rem 0; }
    .doc-footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid var(--border); font-size: 0.8rem; color: var(--muted); text-align: center; }
    .watermark { position: fixed; bottom: 20px; right: 20px; font-size: 0.75rem; color: rgba(128,128,128,0.5); pointer-events: none; z-index: 1000; }
    `;

    const themes: Record<string, string> = {
      default: `
    :root {
      --bg: #ffffff; --heading: #1a1a2e; --body: #374151; --muted: #6b7280;
      --border: #e5e7eb; --link: #2563eb; --accent: #2563eb;
      --code-bg: #f3f4f6; --code-text: #dc2626; --pre-bg: #1e293b;
      --toc-bg: #f9fafb; --tag-bg: #dbeafe; --tag-text: #1d4ed8;
    }
    body { background: var(--bg); color: var(--body); }`,

      light: `
    :root {
      --bg: #fafafa; --heading: #111827; --body: #374151; --muted: #9ca3af;
      --border: #f3f4f6; --link: #0ea5e9; --accent: #0ea5e9;
      --code-bg: #f0f9ff; --code-text: #0284c7; --pre-bg: #0f172a;
      --toc-bg: #f8fafc; --tag-bg: #e0f2fe; --tag-text: #0369a1;
    }
    body { background: var(--bg); color: var(--body); }`,

      dark: `
    :root {
      --bg: #0f172a; --heading: #f1f5f9; --body: #cbd5e1; --muted: #64748b;
      --border: #1e293b; --link: #60a5fa; --accent: #60a5fa;
      --code-bg: #1e293b; --code-text: #f472b6; --pre-bg: #020617;
      --toc-bg: #1e293b; --tag-bg: #1e3a5f; --tag-text: #93c5fd;
    }
    body { background: var(--bg); color: var(--body); }`,

      professional: `
    :root {
      --bg: #ffffff; --heading: #0f172a; --body: #1e293b; --muted: #475569;
      --border: #cbd5e1; --link: #1d4ed8; --accent: #1d4ed8;
      --code-bg: #f1f5f9; --code-text: #be123c; --pre-bg: #0f172a;
      --toc-bg: #f8fafc; --tag-bg: #e2e8f0; --tag-text: #334155;
    }
    body { background: var(--bg); color: var(--body); font-family: Georgia, 'Times New Roman', Times, serif; }`,
    };

    return base + (themes[theme] ?? themes['default']);
  }
}
