import puppeteer, { Browser } from 'puppeteer';
import { IExporter, ExportableDocument } from './exporter.interface';
import { ExportOptions } from '../models/exportJob.model';
import { HtmlExporter } from './html.exporter';
import { logger } from '../lib/logger';

export class PdfExporter implements IExporter {
  private htmlExporter: HtmlExporter;
  private static browserInstance: Browser | null = null;

  constructor() {
    this.htmlExporter = new HtmlExporter();
  }

  async export(document: ExportableDocument, options: ExportOptions): Promise<Buffer> {
    logger.debug('PdfExporter.export called', { documentId: document.id });

    // Reuse the HTML exporter to produce a full HTML page
    const htmlBuffer = await this.htmlExporter.export(document, options);
    const html = htmlBuffer.toString('utf-8');

    const browser = await this.getBrowser();
    const page = await browser.newPage();

    try {
      await page.setContent(html, { waitUntil: 'networkidle0', timeout: 30000 });

      // Inject print-specific CSS overrides
      await page.addStyleTag({
        content: `
          @media print {
            .watermark { position: fixed; bottom: 20px; right: 20px; opacity: 0.3; font-size: 10px; }
            pre { white-space: pre-wrap; word-break: break-word; }
            a { color: inherit !important; text-decoration: none; }
            .toc a::after { content: none; }
          }
        `,
      });

      const pdfBuffer = await page.pdf({
        format: 'A4',
        printBackground: true,
        margin: {
          top: '20mm',
          right: '20mm',
          bottom: '20mm',
          left: '20mm',
        },
        displayHeaderFooter: true,
        headerTemplate: `
          <div style="font-size:9px; color:#aaa; width:100%; text-align:center; padding: 0 20mm;">
            ${this.escapeHtml(document.title)}
          </div>`,
        footerTemplate: `
          <div style="font-size:9px; color:#aaa; width:100%; text-align:center; padding: 0 20mm;">
            Page <span class="pageNumber"></span> of <span class="totalPages"></span>
            &nbsp;&nbsp;&bull;&nbsp;&nbsp; Generated by DevDocs Studio
          </div>`,
        tagged: true,
        outline: true,
      });

      return Buffer.from(pdfBuffer);
    } finally {
      await page.close();
    }
  }

  // ── Browser lifecycle ──────────────────────────────────

  private async getBrowser(): Promise<Browser> {
    if (PdfExporter.browserInstance && PdfExporter.browserInstance.connected) {
      return PdfExporter.browserInstance;
    }

    logger.info('Launching Puppeteer browser instance');

    PdfExporter.browserInstance = await puppeteer.launch({
      headless: true,
      args: [
        '--no-sandbox',
        '--disable-setuid-sandbox',
        '--disable-dev-shm-usage',
        '--disable-accelerated-2d-canvas',
        '--disable-gpu',
        '--window-size=1280,1024',
      ],
    });

    PdfExporter.browserInstance.on('disconnected', () => {
      logger.warn('Puppeteer browser disconnected');
      PdfExporter.browserInstance = null;
    });

    return PdfExporter.browserInstance;
  }

  static async closeBrowser(): Promise<void> {
    if (PdfExporter.browserInstance) {
      await PdfExporter.browserInstance.close();
      PdfExporter.browserInstance = null;
      logger.info('Puppeteer browser closed');
    }
  }

  // ── Helper ─────────────────────────────────────────────

  private escapeHtml(text: string): string {
    return text
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }
}
